component_depth: 3
languages:
- cpp
  production:
    include:
      - /src/.*\.cpp
      - /src/.*\.h
  test:
    include:
      - /test/.*\.cpp
      - /test/.*\.inc
      - /test/.*\.h
exclude:
  - /debian/.*
  - /doc/.*
  - /examples/.*
  - /fonts/.*
  - /icon/.*
  - /logo/.*
  - /m4/.*
  - /scripts/.*
  - /src/.*
  - /build.sh
  - /ltmain.sh

