component_depth: 1
languages:
- cpp
  production:
    include:
      - /src/.*
  test:
    include:
      - /test/.*
exclude:
  - /debian/.*
  - /doc/.*
  - /examples/.*
  - /fonts/.*
  - /icon/.*
  - /logo/.*
  - /m4/.*
  - /scripts/.*
  - /src/.*
  - /build.sh
  - /ltmain.sh

