extraction:
  cpp:
    prepare:
      packages:
        - autoconf-archive
    configure:
      command:
        - autoreconf -v --install --force
        - ./configure --prefix=/usr CPPFLAGS="-DDEBUG" CXXFLAGS="-g -O0 -DDEBUG -W -Wall -pedantic"
    index:
      build_command:
        - make V=1 -j10

