language: cpp
dist: trusty
sudo: required
compiler:
  - gcc

addons:
  apt:
    sources:
     - ubuntu-toolchain-r-test
    packages:
     - g++-7
     - autotools-dev
     - automake
     - autoconf
     - autoconf-archive
     - libtool
     - pkg-config
     - libglib2.0-dev
     - libncurses5-dev
     - gpm
     - libgpm-dev
     - gperf
     - libcppunit-dev
  homebrew:
    packages:
      - autoconf-archive
    update: true

env:
  global:
  # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
  #   via the "travis encrypt" command using the project repo's public key
  - secure: |-
      wvCvMaIm7LoSyWHmpRXvJIetdMnJKsLLxuon6r6BSfpyimoz5FIMEhNhfSt2psv8tJHZgN
      /FcMcLhnTuTMIjvtlEtb3syfHDaNs7S2q3rm6LCmuIUU4ECAwAorkMQbXcyh5rgPlDMDiw
      CyBE8O1yFQebAFxRoP181+0uI2IiIP/8EW3P5PDSQzds+9fnnwrFS+OeBoUZfxT0F2kj2f
      kMXZN4+KmeVIrkqtj8hlRcicLgBPm4hrK5IEUcFLtAbzPj72wkV1duiYG6kqDsATmzMK0m
      5EuMhQ/nL/rbSjhrcRZzPFQ7P31ToSwg1I6cyhMjyXSbpwdppZ/RSwTpqDCdq9l4bDDmvI
      qizdwYZKcDtyHxm4Zl/LZKwWDsGEelcmuJKfdu+QuTgInGNlqulmDykvbsrk9jTimIzHTb
      F8TOn9IpANlTWmvunGeOarvR9qJReZcwSMq41hdMbsUdHiC1arZjKvINcPVuwikzaNq4iA
      te6mtSdrfdx1wLxQ6ZYNgKd9hz+uUTlBYl80hkATmq0NPnPQw2KzyG9E6nLrKOy2M0ozO8
      bL/epiiMBKJ37X1UcRU4WZYq+peLME8EefcPcXOSWNLwJtR7mtON8uMBrLL9CWmRMFD5Hy
      lQYALW2DhCnDBROKB3gxB/VkBGFNE0IPGeDtBGbLqDtKWPQoL125I=

matrix:
  include:
  #
  # Coverity Scan
  #
  - os: linux
    env:
      - TEST="Coverity Scan"
      - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    addons:
      coverity_scan:
        project:
          name: gansm/finalcut
          description: Build submitted via Travis CI
        notification_email: guru.mail@muenster.de
        build_command_prepend: "autoreconf -v --install --force && ./configure --prefix=/usr CPPFLAGS='-DDEBUG' CXXFLAGS='-g -O0 -DDEBUG -DUNIT_TEST' --with-unit-test && make clean"
        build_command: "make V=1 -j10"
        branch_pattern: master
    before_install:
      - eval "${MATRIX_EVAL}"
      - lsb_release -a
      - uname -a
      - whoami
      - sudo apt-get install g++-7 gpm libgpm-dev libcppunit-dev autoconf-archive
      # Work around broken certificate of scan.coverity.com
      - sudo curl -s -L https://entrust.com/root-certificates/entrust_l1k.cer -o /usr/local/share/ca-certificates/entrust_l1k.crt
      - sudo update-ca-certificates
    script:
      - autoreconf -v --install --force
      - ./configure --prefix=/usr CPPFLAGS="-DDEBUG" CXXFLAGS="-g -O0 -DDEBUG -DUNIT_TEST" --with-unit-test
      - make V=1 -j10
      - make check
      - cat test/*.log

  #
  # Coveralls + Codecov
  #
  - os: linux
    env:
      - TEST="Coveralls"
      - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    before_install:
      - eval "${MATRIX_EVAL}"
      - lsb_release -a
      - uname -a
      - pip install --user cpp-coveralls
      - sudo pip install codecov
    script:
      - ./build.sh coverage
    after_success:
      - coveralls --gcov-options '\-lp' -e debian -e doc -e icon -e logo -e m4 -e scripts -e examples
      - bash <(curl -s https://codecov.io/bash)

  #
  # macOS
  #
  - os: osx
    env:
      - TEST="macOS"
    script:
      - uname -a
      - autoreconf -v --install --force
      - ./configure --prefix=/usr
      - make -j10

